name: llm2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pybind11-abi=4=hd3eb1b0_1
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - scipy=1.13.1=py310h5f9d8c6_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.27.2
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aioprometheus==23.12.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.21.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - emoji==2.14.0
      - evomerge==0.1.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.4
      - fasttext==0.9.3
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - fugashi==1.3.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.26.2
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - neologdn==0.5.3
      - networkx==3.4.2
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - orjson==3.10.11
      - packaging==24.1
      - pandas==2.2.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - propcache==0.2.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - pyarrow==18.0.0
      - pybind11==2.13.6
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pynvml==11.5.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.17
      - pytz==2024.2
      - pyyaml==6.0.2
      - quantile-python==1.1
      - ray==2.38.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rouge-score==0.1.2
      - rpds-py==0.21.0
      - ruff==0.7.2
      - safetensors==0.4.5
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - starlette==0.41.2
      - sympy==1.13.3
      - tokenizers==0.20.3
      - tomlkit==0.12.0
      - torch==2.1.2
      - tqdm==4.67.0
      - transformers==4.46.2
      - triton==2.1.0
      - typer==0.13.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - unidic-lite==1.0.8
      - urllib3==2.2.3
      - uvicorn==0.32.0
      - uvloop==0.21.0
      - vllm==0.3.0+cu126
      - wandb==0.18.6
      - watchfiles==0.24.0
      - websockets==12.0
      - xformers==0.0.23.post1
      - xxhash==3.5.0
      - yarl==1.17.1
prefix: /home/K2064083/miniconda3/envs/llm2
